@startuml energy-card-relationships

entity "artist" as artist {}
entity "energy_basic" as energy_basic {}
entity "energy_special" as energy_special {}
entity "extended_attributes_special_pokemon" as extended_attributes_special_pokemon {}
entity "extended_attributes_special_pokemon_type" as extended_attributes_special_pokemon_type {}
entity "rarity" as rarity {}
entity "set" as set {}

energy_card ||..up|| artist
energy_card ||..|| energy_basic
energy_card ||..|| energy_special
energy_card ||..left|| extended_attributes_special_pokemon
energy_card ||..right|| extended_attributes_special_pokemon_type
energy_card ||..up|| rarity
energy_card ||..up|| set

@enduml